In [2]:
import pandas as pd

df_la_list = pd.read_csv('airbnb_data/la_listings.csv')
df_z_rent = pd.read_csv('airbnb_data/Zip_zori_sm_month.csv')
df_z_sale = pd.read_csv('airbnb_data/Metro_median_sale_price_uc_sfrcondo_sm_month.csv')

In [4]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,36978719,https://www.airbnb.com/rooms/36978719,20230903194229,2023-09-04,previous scrape,Home in Alhambra · 1 bedroom · 1 bed · 1 bath,NaN,NaN,https://a0.muscache.com/pictures/7d2f2cda-fa0e...,278008181,...,NaN,NaN,NaN,NaN,f,3,0,2,1,NaN
1,930487087555321292,https://www.airbnb.com/rooms/930487087555321292,20230903194229,2023-09-04,previous scrape,Home in La Puente · ★New · 1 bedroom · 1 bed ·...,Take a break and unwind at this peaceful oasis.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,482579539,...,NaN,NaN,NaN,NaN,f,9,0,9,0,NaN
2,942342470598573002,https://www.airbnb.com/rooms/942342470598573002,20230903194229,2023-09-04,city scrape,Home in Rowland Heights · ★New · 1 bedroom · 2...,在这处宁静房源中，与全家人尽情放松。,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,495867643,...,NaN,NaN,NaN,NaN,t,4,0,4,0,NaN
3,41240375,https://www.airbnb.com/rooms/41240375,20230903194229,2023-09-04,city scrape,Condo in Los Angeles · 1 bedroom · 1 bed · 1.5...,Cozy condo only 10 minutes walking to the wate...,NaN,https://a0.muscache.com/pictures/4e9e16ac-2776...,21981097,...,5.0,5.0,5.0,NaN,f,1,1,0,0,0.04
4,632034182071149887,https://www.airbnb.com/rooms/632034182071149887,20230903194229,2023-09-04,city scrape,Condo in Beverly Hills · 2 bedrooms · 2 beds ·...,Location! Location…luxury in the midst of Beve...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,232012515,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44594 entries, 0 to 44593
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            44594 non-null  int64
 1   listing_url                                   44594 non-null  object
 2   scrape_id                                     44594 non-null  int64
 3   last_scraped                                  44594 non-null  object
 4   source                                        44594 non-null  object
 5   name                                          44594 non-null  object
 6   description                                   43937 non-null  object
 7   neighborhood_overview                         25053 non-null  object
 8   picture_url                                   44594 non-null  object
 9   host_id                                       44594 non-null  int64
 10  host_url                                      44594 non-null  object
 11  host_name                                     44592 non-null  object
 12  host_since                                    44592 non-null  object
 13  host_location                                 34044 non-null  object
 14  host_about                                    24684 non-null  object
 15  host_response_time                            35164 non-null  object
 16  host_response_rate                            35164 non-null  object
 17  host_acceptance_rate                          35610 non-null  object
 18  host_is_superhost                             43515 non-null  object
 19  host_thumbnail_url                            44592 non-null  object
 20  host_picture_url                              44592 non-null  object
 21  host_neighbourhood                            34730 non-null  object
 22  host_listings_count                           44592 non-null  float64
 23  host_total_listings_count                     44592 non-null  float64
 24  host_verifications                            44594 non-null  object
 25  host_has_profile_pic                          44592 non-null  object
 26  host_identity_verified                        44592 non-null  object
 27  neighbourhood                                 25054 non-null  object
 28  neighbourhood_cleansed                        44594 non-null  object
 29  neighbourhood_group_cleansed                  44594 non-null  object
 30  latitude                                      44594 non-null  float64
 31  longitude                                     44594 non-null  float64
 32  property_type                                 44594 non-null  object
 33  room_type                                     44594 non-null  object
 34  accommodates                                  44594 non-null  int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                44569 non-null  object
 37  bedrooms                                      31251 non-null  float64
 38  beds                                          44091 non-null  float64
 39  amenities                                     44594 non-null  object
 40  price                                         44594 non-null  object
 41  minimum_nights                                44594 non-null  int64
 42  maximum_nights                                44594 non-null  int64
 43  minimum_minimum_nights                        44594 non-null  int64
 44  maximum_minimum_nights                        44594 non-null  int64
 45  minimum_maximum_nights                        44594 non-null  int64
 46  maximum_maximum_nights                        44594 non-null  int64
 47  minimum_nights_avg_ntm                        44594 non-null  float64
 48  maximum_nights_avg_ntm                        44594 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              44594 non-null  object
 51  availability_30                               44594 non-null  int64
 52  availability_60                               44594 non-null  int64
 53  availability_90                               44594 non-null  int64
 54  availability_365                              44594 non-null  int64
 55  calendar_last_scraped                         44594 non-null  object
 56  number_of_reviews                             44594 non-null  int64
 57  number_of_reviews_ltm                         44594 non-null  int64
 58  number_of_reviews_l30d                        44594 non-null  int64
 59  first_review                                  32962 non-null  object
 60  last_review                                   32962 non-null  object
 61  review_scores_rating                          32962 non-null  float64
 62  review_scores_accuracy                        32731 non-null  float64
 63  review_scores_cleanliness                     32732 non-null  float64
 64  review_scores_checkin                         32724 non-null  float64
 65  review_scores_communication                   32731 non-null  float64
 66  review_scores_location                        32723 non-null  float64
 67  review_scores_value                           32720 non-null  float64
 68  license                                       11552 non-null  object
 69  instant_bookable                              44594 non-null  object
 70  calculated_host_listings_count                44594 non-null  int64
 71  calculated_host_listings_count_entire_homes   44594 non-null  int64
 72  calculated_host_listings_count_private_rooms  44594 non-null  int64
 73  calculated_host_listings_count_shared_rooms   44594 non-null  int64
 74  reviews_per_month                             32962 non-null  float64
dtypes: float64(18), int64(21), object(36)
memory usage: 25.5+ MB

In [7]:
df['price']

0         $90.00
1         $35.00
2         $69.00
3        $120.00
4        $450.00
          ...
44589    $510.00
44590    $168.00
44591     $85.00
44592    $508.00
44593    $480.00
Name: price, Length: 44594, dtype: object

In [3]:
df_z_rent.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2015-01-31,...,2022-10-31,2022-11-30,2022-12-31,2023-01-31,2023-02-28,2023-03-31,2023-04-30,2023-05-31,2023-06-30,2023-07-31
0,91982,1,77494,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Fort Bend County,1670.679580,...,2075.255234,2061.137924,2069.625818,2103.173183,2118.118682,2123.200935,2089.117986,2096.496744,2105.715103,2119.451238
1,91940,3,77449,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Harris County,1274.676753,...,1811.102740,1773.456256,1772.820748,1762.328884,1772.942839,1784.288476,1784.750453,1789.217743,1799.360782,1807.361463
2,91733,5,77084,zip,TX,TX,Houston,"Houston-The Woodlands-Sugar Land, TX",Harris County,NaN,...,1711.522493,1726.142851,1717.839329,1719.081915,1717.283184,1733.740666,1745.658694,1762.497318,1768.142390,1764.616554
3,93144,6,79936,zip,TX,TX,El Paso,"El Paso, TX",El Paso County,NaN,...,1435.609267,1446.655608,1441.710282,1482.989181,1496.340115,1493.516892,1481.837008,1487.743808,1491.369615,1512.230159
4,62093,7,11385,zip,NY,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,NaN,...,2990.216342,2951.041683,2911.259994,2869.472729,2848.934383,2857.651192,2890.163751,2941.074493,2982.382380,3008.639996

In [4]:
df_z_rent.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6884 entries, 0 to 6883
Columns: 112 entries, RegionID to 2023-07-31
dtypes: float64(103), int64(3), object(6)
memory usage: 5.9+ MB

In [9]:
df_z_rent.loc[[df_z_rent['RegionID'].value_counts()] > 10]

TypeError: '>' not supported between instances of 'list' and 'int'